/**
 * AnimationConfig
 * Pure animation frame-data. No scene.load.* / scene.anims.* calls here.
 * The AnimationSystem reads these and registers Phaser animations in create().
 */

/** Static, single-texture animations keyed exactly as registered. */
export const STATIC_ANIMS = [
  { key: "boom_play", texture: "boom", start: 0, end: 3, frameRate: 16, repeat: 0 },
] as const;

/**
 * Hero walk cycle template. Heroes share one sprite-sheet layout (3 cols x 4
 * rows), so per-texture / per-facing keys are generated by the AnimationSystem
 * from the layout constants in `features/types/HeroRarity`. Only the playback
 * tuning lives here.
 */
export const HERO_WALK_ANIM = {
  frameRate: 8,
  repeat: -1,
} as const;
